#!/bin/bash

# init.sh - Script to initialize the AI Hacking League Backend project
# This script sets up the project directory structure, initializes a Poetry environment,
# installs dependencies, and creates necessary files with boilerplate code.

# Exit immediately if a command exits with a non-zero status
set -e

# Define the project root directory
PROJECT_ROOT="backend"

# Create the project directory
mkdir -p $PROJECT_ROOT

# Navigate into the project directory
cd $PROJECT_ROOT

echo "Creating directory structure..."

# Create the directory structure as per the project layout
mkdir -p app/api/endpoints
mkdir -p app/core
mkdir -p app/db
mkdir -p app/models
mkdir -p app/schemas
mkdir -p app/services
mkdir -p tests/api
mkdir -p tests/services

# Create empty __init__.py files to make directories Python packages
touch app/__init__.py
touch app/api/__init__.py
touch app/api/endpoints/__init__.py
touch app/core/__init__.py
touch app/db/__init__.py
touch app/models/__init__.py
touch app/schemas/__init__.py
touch app/services/__init__.py
touch tests/__init__.py
touch tests/api/__init__.py
touch tests/services/__init__.py

echo "Initializing Poetry environment..."

# Initialize a new Poetry project
poetry init -n \
  --name "ai-hacking-league-backend" \
  --description "Backend for the AI Hacking League application" \
  --author "Your Name <youremail@example.com>" \
  --python "^3.9"

# Add dependencies
poetry add fastapi[all] pydantic supabase fastapi-security pyjwt requests python-dotenv

# Add development dependencies
poetry add --dev pytest pytest-asyncio

echo "Creating pyproject.toml..."

# The pyproject.toml is created by Poetry, but we can customize it if needed
# For this script, we assume the default generated by Poetry is sufficient

echo "Creating .env.example..."

# Create .env.example file with environment variables
cat <<EOL > .env.example
SUPABASE_URL=your_supabase_project_url
SUPABASE_KEY=your_supabase_api_key
GITHUB_TOKEN=your_github_token
SECRET_KEY=your_secret_key
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
EOL

echo "Creating Dockerfile..."

# Create Dockerfile
cat <<EOL > Dockerfile
# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in poetry
RUN pip install --no-cache-dir poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev --no-interaction --no-ansi

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run app.main:app when the container launches
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
EOL

echo "Creating requirements.txt..."

# Export requirements.txt from Poetry
poetry export -f requirements.txt --output requirements.txt --without-hashes

echo "Creating app/main.py..."

# Create main.py with FastAPI app
cat <<EOL > app/main.py
from fastapi import FastAPI
from app.api.api import api_router

app = FastAPI(title="AI Hacking League Backend")

app.include_router(api_router)
EOL

echo "Creating app/api/api.py..."

# Create api.py to include routers
cat <<EOL > app/api/api.py
from fastapi import APIRouter
from app.api.endpoints import auth, challenges, leaderboard, teams, users

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(challenges.router, prefix="/challenges", tags=["challenges"])
api_router.include_router(leaderboard.router, prefix="/leaderboard", tags=["leaderboard"])
api_router.include_router(teams.router, prefix="/teams", tags=["teams"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
EOL

echo "Creating endpoint files..."

# Create auth.py endpoint
cat <<EOL > app/api/endpoints/auth.py
from fastapi import APIRouter, Depends, HTTPException, status
from app.schemas.user import UserCreate, UserOut
from app.core.security import create_access_token
from app.services.supabase_service import supabase_client
from app.models.user import User
from datetime import timedelta

router = APIRouter()

@router.post("/register", response_model=UserOut)
async def register(user_in: UserCreate):
    # Registration logic here
    pass

@router.post("/login")
async def login():
    # Login logic here
    pass

@router.post("/logout")
async def logout():
    # Logout logic here
    pass

@router.get("/me", response_model=UserOut)
async def get_current_user():
    # Get current user logic here
    pass
EOL

# Similarly, create other endpoint files (challenges.py, leaderboard.py, teams.py, users.py)
# For brevity, only creating placeholders with pass statements

echo "Creating challenges.py endpoint..."

cat <<EOL > app/api/endpoints/challenges.py
from fastapi import APIRouter, Depends, HTTPException, status
from app.schemas.challenge import ChallengeCreate, ChallengeOut
from app.services.supabase_service import supabase_client
from app.models.challenge import Challenge

router = APIRouter()

@router.get("/", response_model=List[ChallengeOut])
async def list_challenges():
    # List challenges logic here
    pass

# Additional endpoints...
EOL

# Repeat for leaderboard.py, teams.py, users.py

echo "Creating core configuration files..."

# Create config.py
cat <<EOL > app/core/config.py
import os
from dotenv import load_dotenv
load_dotenv()

class Settings:
    SUPABASE_URL: str = os.getenv("SUPABASE_URL")
    SUPABASE_KEY: str = os.getenv("SUPABASE_KEY")
    GITHUB_TOKEN: str = os.getenv("GITHUB_TOKEN")
    SECRET_KEY: str = os.getenv("SECRET_KEY")
    ALGORITHM: str = os.getenv("ALGORITHM", "HS256")
    ACCESS_TOKEN_EXPIRE_MINUTES: int = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 30))

settings = Settings()
EOL

# Create security.py
cat <<EOL > app/core/security.py
from datetime import datetime, timedelta
from jose import jwt
from app.core.config import settings

def create_access_token(data: dict, expires_delta: timedelta = None):
    to_encode = data.copy()
    expire = datetime.utcnow() + expires_delta if expires_delta else datetime.utcnow() + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
    return encoded_jwt
EOL

echo "Creating database session files..."

# Create base.py (empty for now)
touch app/db/base.py

# Create session.py
cat <<EOL > app/db/session.py
# Database session management
EOL

echo "Creating models..."

# Create user.py model
cat <<EOL > app/models/user.py
from pydantic import BaseModel
from uuid import UUID
from datetime import datetime

class User(BaseModel):
    id: UUID
    username: str
    email: str
    hashed_password: str
    is_active: bool
    is_superuser: bool
    created_at: datetime
    updated_at: datetime
EOL

# Similarly, create challenge.py and team.py models

echo "Creating schemas..."

# Create user.py schema
cat <<EOL > app/schemas/user.py
from pydantic import BaseModel, EmailStr
from uuid import UUID

class UserCreate(BaseModel):
    username: str
    email: EmailStr
    password: str

class UserOut(BaseModel):
    id: UUID
    username: str
    email: EmailStr
EOL

# Similarly, create challenge.py and team.py schemas

echo "Creating services..."

# Create supabase_service.py
cat <<EOL > app/services/supabase_service.py
from supabase import create_client
from app.core.config import settings

supabase_client = create_client(settings.SUPABASE_URL, settings.SUPABASE_KEY)

# Define functions to interact with Supabase
EOL

# Create github_service.py
cat <<EOL > app/services/github_service.py
import requests
from app.core.config import settings

# Define functions to interact with GitHub API
EOL

echo "Creating tests..."

# Create conftest.py
cat <<EOL > tests/conftest.py
import pytest

# Define fixtures for testing
EOL

echo "Initialization complete!"
